### ISSUE TITLE
Feature request: Support animated jetways

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#1]
Support animated jetways http://wiki.flightgear.org/Jetway

**Comment by merspieler** [comment]
This has NOT been fixed, please reopen

**Comment by legoboyvdlp** [comment]
I am fairly sure I did this already, are you sure?

**Comment by merspieler** [comment]
On master (commit 02897e0 ) at KSFO Gate 101: https://s20.postimg.cc/fnostcs3v/fgfs-screen-017.png

**Comment by legoboyvdlp** [comment]
Alright! I obviously did not do it then ;)
