### ISSUE TITLE
APU doesn't delay shutdown if bleed was used

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#10]
### Expected Behavior
If the APU bleed was used, the shutdown of he APU is delayed for cool down.

### Current Behavior
The APU turns out emideatly

### Steps to Reproduce
1. Start APU with APU bleed
2. Turn APU off

**Comment by legoboyvdlp** [comment]
As far as I know, 2018.2 has some JSBSIM improvements that will allow the simulation of the APU as a real JSBSIM engine, with a few lbs of thrust as well!

This can be revisited once the APU is simulated that way, as the way I once did it, with settimer and interpolate, was very messy and broke the APU.

**Comment by merspieler** [comment]
:D you're speaking of 2018.2 when 2018.1 isn't even released yet...

**Comment by it0uchpods** [comment]
heh
Well, the logic for that is completely missing. I can add it pretty easily, set a flag if the bleed is used, then have a timeout. I've put it on my list, so probably you will see this fix soon.

Josh

**Comment by merspieler** [comment]
Any update on this?

**Comment by it0uchpods** [comment]
No. Be patient. I'm busy.

**Comment by it0uchpods** [comment]
I have time to implement this, just need to find the delay time first.

J

**Comment by merspieler** [comment]
delay time = 2 min

(I'm looking for the fcom ref)

**Comment by it0uchpods** [comment]
Yeah, that's what I found too. :D
On its way.

**Comment by it0uchpods** [comment]
This is next in the fix-list.
