### ISSUE TITLE
APU fuel consumption [severity: minor]

### ISSUE THREAD

**Issue by pumuckl11** [it0uchpods/IDG-A32X#101]
### Expected Behavior

APU uses fuel when running with FOB decreasing
(=> impacts fuel planning)

### Current Behavior

APU doesn't use fuel at all

### Steps to Reproduce

1. while on ground have APU running with engines shut down
2. increase simulation speed
3. observe FOB not changing

**Comment by it0uchpods** [comment]
It's not added yet. Fuel system overhaul is in progress, when it's done, it will be implemented.

Closed -- as it's not a bug.

Kind Regards,
Josh
