### ISSUE TITLE
PFD overspeed strip (rev. 4040)

### ISSUE THREAD

**Issue by pumuckl11** [it0uchpods/IDG-A32X#102]
### Expected Behavior

above FL240 overspeed strip is sitting on M.82

### Current Behavior

overspeed strip sticks with VMO (= 350) regardless altitude

### Steps to Reproduce

1. level flight FL200@350kt with AP/ATHR on
2. select ALT FL300
3. select mode OP CLB

starting at about FL240 aircraft will exceed MMO (= M.82) without overspeed indication

**Comment by it0uchpods** [comment]
OK, will fix.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
It could be fixed now. I wasn't able to test because I am not in a PC which can't.

Kind Regards,
Josh

**Comment by pumuckl11** [comment]
fix not quite successful

approaching FL240 overspeed strip will now move down following MMO, but climbing through around FL240@350 (VMO = MMO) causes overspeed strip to get stuck at VMO

**Comment by it0uchpods** [comment]
Screenshot?

It should show VMO or MMO, whichever is lower.

J

**Comment by pumuckl11** [comment]
sure



![below_fl240](https://user-images.githubusercontent.com/33175825/33334585-acf09036-d46a-11e7-9256-524d9b4c7d04.png)


![above_fl240](https://user-images.githubusercontent.com/33175825/33334603-be4685ca-d46a-11e7-8f5f-0e89ad59a426.png)

**Comment by it0uchpods** [comment]
Hmm, seems I made it backwards. I am home now. Turns out I put the condition backwards.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
OK, it's fixed! Thanks for your help

Kind Regards,
Josh

**Comment by pumuckl11** [comment]
don't mention it
(confirmed rev. 4041)
