### ISSUE TITLE
Autobreak doesn't work if RevTHR is applied

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#105]
### Expected Behavior
AutoBRK should work

### Current Behavior
AutoBRK isjust elected and doesn't decel

### Steps to Reproduce
1. Start a flight
2. On approach enable autoBRK
3. On touchdown applie reversTHR befor the noseweel touches the ground
4. AutoBRK will not break

**Comment by legoboyvdlp** [comment]
How do you know that it does not **brake**?
Also, you generally would want to apply reverse from nosewheel touchdown. 

Autobrake systems do **not** command a braking force: they command a deceleration force. If you are on a light aircraft, landing slower (say 133 knots), with ground spoilers, and maximum reverse thrust, and autobrake LO, you probably won't even get ANY braking input at all!

**Comment by merspieler** [comment]
ok... i didn't kenw that... it just downt show the `decel` and when i put THR to IDLE the autobreak doesn't break

**Comment by legoboyvdlp** [comment]
OK, that's a bug, then :)
Right now, the autobrake is really basic, and just uses brakes... it's not dynamic like in the real Airbus, so it doesn't know to reduce brake output with reverse thrust and so on. It will be improved. it0uchpods is sleeping right now, as it is about 6AM where he is: he'll be around in a couple of hours or so :)

**Comment by merspieler** [comment]
ok... it isn't a major bug (nohigh priority)... just something i recognized when flying

**Comment by it0uchpods** [comment]
Got it... Will fix shortly, thanks!

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Fixed, will make it more complex later on with proper decel rate.

Kind Regards,
Josh
