### ISSUE TITLE
ND sreen bug

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#106]
### Expected Behavior
Those flickering lines to be not there

### Current Behavior
There are some flickering lines on the ND
This happens since today (haven't flewn yesterday so somewhere there must be the mistake)

Some screenshots:
![img1](https://s33.postimg.org/velfglcr1/fgfs-screen-001.png)
As you can see here, the flickering line isn't on the flightplan line but a bit besides it.
![img2](https://s33.postimg.org/xvx6ny4e5/fgfs-screen-002.png)
![img3](https://s33.postimg.org/ri83kocct/fgfs-screen-003.png)
![img4](https://s33.postimg.org/56aarakyl/fgfs-screen-004.png)

**Comment by legoboyvdlp** [comment]
Definitely a bug... it0uchpods will take a look in a while :smile:

**Comment by it0uchpods** [comment]
Known bug, unknown cause. Will keep looking into it.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Been looking into it, it appears to happen only in ARC mode, is that right?

So far, it has eluded me.

Kind Regards,
Josh

**Comment by merspieler** [comment]
No, I've seen it in NAV as well

**Comment by it0uchpods** [comment]
OK.
J

**Comment by it0uchpods** [comment]
Added this to the long-term-issue scheduler. Closing here for now.

Kind Regards,
Josh
