### ISSUE TITLE
Direction of movement on the Alt scale and VSI show is somethimes diffrent

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#108]
### Expected Behavior
The Alt Scale moves up (from counting numbers point of view) if the VSI points up and the other way around

### Current Behavior
In some rare cases (wasn't able to reproduce, mostly when i'm a bit(~300ft) above CRZ ALT) the VSI shows me some downward movement but the Alt scale still moves up.

**Comment by it0uchpods** [comment]
Hi
Yes, I'm aware of this. I use the FG instrument files, so it's a bug in FlightGear and not in the Airbus. I will work on a custom VSI calculation later probably.

Kind Regards,
Josh
