### ISSUE TITLE
AUTO BRK MAX doesn't work in flight

### ISSUE THREAD

**Issue by Darkriser** [it0uchpods/IDG-A32X#109]
I'm able to select AUTO BRK MAX on ground (for the case of TO abort), however unable to select it when in flight (during preparation for landing).

### Expected Behavior
AUTO BRK MAX btn available in flight

### Current Behavior
Ignores mouse click

### Possible Solution
n/a

### Steps to Reproduce
1. get in the air
2. click AUTO BRK MAX btn

**Comment by it0uchpods** [comment]
This is correct behavior.

MAX can only be selected on ground.

Kind Regards,
Josh

**Comment by merspieler** [comment]
Post 8 [here](https://www.pprune.org/tech-log/245897-airbus-auto-brake-system.html) in states the same but others say, they have observed something different.
So somehow it is possible

**Comment by it0uchpods** [comment]
Not in the A320 version we are modelling. There are many versions of the airplane, the one we are modelling does not have MAX in the air.

Kind Regards,
Josh

PS: Going to check the behavior for A330.
