### ISSUE TITLE
EXT PWR don't show V and HZ when avail

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#11]
Please fix in LowerECAM

### Expected Behavior
When EXT PWR is avail but isn't used as power source for AC1 or AC2 V and HZ are still shown.

### Current Behavior
When avail, (not used) the V and HZ are 0

_Note: the APU GEN has the same problem when EXT PWR is used as source._

### Steps to Reproduce
1. Connect the GPU
2. Look at the ELEC page on the LECAM

**Comment by merspieler** [comment]
Was not fixed, please reopen

**Comment by it0uchpods** [comment]
Issues page only for master.

**Comment by merspieler** [comment]
The issue exists in master as well

**Comment by it0uchpods** [comment]
There is no elec page, so it doesn't matter.

**Comment by merspieler** [comment]
But it is there and it will be reopened sooner or later

**Comment by merspieler** [comment]
But it is there and it will be reopened sooner or later
