### ISSUE TITLE
"To low, Flaps" on flaps 3 landing

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#114]
### Expected Behavior
No alert

### Current Behavior
The "To low, flaps" callout comes

### Steps to Reproduce
1. fly appr with managed spd
2. activate `ldg flap 3` on the gpws sction on the ohp
3. continue appr and extend flaps just to 3
4. listen to the callouts

**Comment by it0uchpods** [comment]
Changed Status to Confirmed.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Fixed later today.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Fixed.

Kind Regards,
Josh
