### ISSUE TITLE
APU doesn't power controlls

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#116]
### Expected Behavior
APU keeps the plane controllable like in the Hudson river incident.

### Current Behavior
On ENG fail without RAT the plane can not be controlled any more

### Steps to Reproduce
1. Start with APU running (or, not yet simulated, in time of reduced power supply from ENGs while spinning down after they turned off &lt;aka bird strike&gt;)
2. Try to controll the AC
3. Turn APU off -> RAT extends
4. AC is controllable again

**Comment by it0uchpods** [comment]
Changed status to confirmed

For some reason, even though the electrical is powered, the blue hydraulics is not operating. When I turn the yellow hydraulics on electrics, it powers up, and PTU powers the green --> good.

But blue won't get power, and flybywire did not upgrade to Direct Law from Mechanical.

So you found many bugs here! Thank you!

Will work on them in the next few days.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Corrected. Thank you!

Kind Regards,
Josh
