### ISSUE TITLE
FDM BRANCH side wind tends to through the plane around

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#117]
### Expected Behavior
Doesn't flip to one side

### Current Behavior
The plane gets thrown to the side by the wind

### Steps to Reproduce
1. go somewhere with strong winds (40-50kn)
2. taxi with the wind coming from the side

**Comment by it0uchpods** [comment]
Unable to reproduce
Video or picture please.
Tried 50kts at 90deg.

The pushes a bit, but with rudder, can correct.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Changed status to confirmed
@legoboyvdlp has reproduced it. I am working on it.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Fixed.
In git within the hour.

Kind Regards,
Josh
