### ISSUE TITLE
ECAM memo after landing and show up to early

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#118]
### Expected Behavior
The TO memo should apear about 2min after the 2nd ENG started
After langing no to memo is shown

### Current Behavior
To memo is shown while 2nd ENG is still starting and shown after landing

### Steps to Reproduce
1. Fly a normal flight and observe the ECAM msg section

**Comment by legoboyvdlp** [comment]
This is known, and will be corrected soon.

**Comment by it0uchpods** [comment]
Fixed. (Commit coming in a few mins)

Kind Regards,
Josh
