### ISSUE TITLE
AUTO BRK MAX isn't disengaged by gear retraction

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#119]
### Expected Behavior
On gear retraction the AUTO BRK MAX should disengage

### Current Behavior
It stays on

### Steps to Reproduce
1. TO and watch AUTO BRK MAX indecator on gear retraction

**Comment by it0uchpods** [comment]
OK, fixed in the internal build, in the next revision it's in git.

Thanks for all your bug reports, much appreciated. 

Kind Regards,
Josh
