### ISSUE TITLE
AC ESS FEED push button should be FAULT|ALTN 

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#120]
### Expected Behavior
AC ESS FEED push button should be labled FAULT|ALTN

### Current Behavior
It's labeled FAULT|OFF

### Steps to Reproduce
1. Set ANN LT to TEST
2. Look at the AC ESS FEED push button

**Comment by it0uchpods** [comment]
Do you have a source for that? The picture I took of the revision we are modelling reads FAULT|OFF. (Keep in mind, 321/319 might be different, this is 320.)

Kind Regards,
Josh

**Comment by merspieler** [comment]
Source CBT video from nov 2016.
I'll check that, if you thell me, which revision you model.

**Comment by it0uchpods** [comment]
The plane I got most of my pictures and information on was MSN5142, so that is what we are aiming for. But some information had to come from a slightly older/newer MSN.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Fixed (thanks for to you)
And also fixed the ESS bus logic -- it was wrong.

Kind Regards,
Josh
