### ISSUE TITLE
Both APs can be on

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#121]
### Expected Behavior
Only on approach both APs can be on

### Current Behavior
In normal flight, both APs can be on.

### Steps to Reproduce
1. Start a flight and turn both APs on

**Comment by it0uchpods** [comment]
What happens when you try to turn one on while another is on?

Kind Regards,
Josh

**Comment by merspieler** [comment]
it goes on

**Comment by it0uchpods** [comment]
And the first one goes off?

Josh

**Comment by merspieler** [comment]
no

**Comment by it0uchpods** [comment]
That is what it does now.  :confused: 

Josh

**Comment by it0uchpods** [comment]
It's fixed. Now only dual APs are supported once APPR is armed, or G/S is active.

Kind Regards,
Josh
