### ISSUE TITLE
EGPWS's "Too low, Terrain!" can be heared even if GPWS is off

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#122]
### Expected Behavior
When GPWS is off, no alert should be triggerd

### Current Behavior
The "Too low, Terrain!" still comes

### Steps to Reproduce
1. Turn off `GPWS SYS`
2. Fly in a way that triggers the EGPWS (eg. fly the Grand Canyon)
3. Listen to the callout

**Comment by it0uchpods** [comment]
Did this happen just recently, or did you just notice it happened recently? I need to know if I may have broken it.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Nevermind, fixed it.

Kind Regards,
Josh
