### ISSUE TITLE
Gear is not shown in MP

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#123]
### Expected Behavior
Gear is shown in MP

### Current Behavior
The gear isn't shown

### Steps to Reproduce
1. Join MP
2. Let someone else look at it

**Comment by it0uchpods** [comment]
I do not have this issue. I will test it as soon as possible and report back.

Kind Regards,
Josh

**Comment by merspieler** [comment]
same happens with the A330

**Comment by merspieler** [comment]
If the player that looks at the plane see the correct gear, toggle the gear an take a look at it again.
If join with gear dn and then the gear is retracted, it's still shown as dn.

**Comment by it0uchpods** [comment]
In the group flight with JMaverick, I saw an A320 takeoff, put its gear up, then climb, and then I saw it in cruise with no gears. On final, the gears came out, and it worked fine.

Cannot reproduce.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Cannot reproduce. 

Closed.
Josh

**Comment by merspieler** [comment]
well. maybe try it with OR+ORCAM

**Comment by it0uchpods** [comment]
Cannot reproduce it. Seems to be only on your system. I'll ask jomo about it sometime. Until I can reproduce it, this stays closed.

Josh

**Comment by merspieler** [comment]
you can look at his videos...

**Comment by it0uchpods** [comment]
I don't have time for that. I am very busy.
Give me time + link and I can look. 

Josh

**Comment by merspieler** [comment]
idc... I don't have time as well... and it's your bug not mine... so do what ever you want
