### ISSUE TITLE
APU shutdown sequenz incorrect, if APU BLEED was on

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#124]
### Expected Behavior
When APU was on and BLEED was used, the APU stays on for 2min for cool down

### Current Behavior
The APU shuts in the same way down, as if no APU BLEED was used

### Steps to Reproduce
1. Start APU
2. Turn APU BLEED on
3. Turn APU BLEED off
4. Turn APU off
5. count time for shutdown

**Comment by it0uchpods** [comment]
Not a bug -- the system works as it was programmed. Please do not post things missing that are in the real plane here.

Kind Regards,
Josh
