### ISSUE TITLE
Low fps

### ISSUE THREAD

**Issue by BAWV12** [it0uchpods/IDG-A32X#130]
I observed large framerate drops in all navigation display modes, after switch off TCAS via property browser, fps rise from 10-15 back to 25-30 as on older version. This problem is on A33x too.
Path to traffic ON/OFF :
/instrumentation/efis/inputs/tfc
/instrumentation/efis[1]/inputs/tfc - when 1, traffic ON, when 0, traffic off

My conclusion :
somewhere in the traffic search algorithm is something time very consumpting.

**Comment by it0uchpods** [comment]
I turned it off for now. Will sort it later, TCAS is on the todo.

Josh

**Comment by BAWV12** [comment]
Thank You.
Turn off TCAS for EFIS[0] and EFIS[1] was on 1st place in my startup checklist ☺

**Comment by it0uchpods** [comment]
You're welcome, thanks for reporting.

Josh 👍

**Comment by BAWV12** [comment]
Are You home, or still in hospital ?

**Comment by it0uchpods** [comment]
Home now. I've got the cold pretty bad also. (😠)
¯\_(ツ)_/¯

Josh

**Comment by BAWV12** [comment]
I wish You quick recovery.

**Comment by it0uchpods** [comment]
Appreciate it 😃 

Josh
