### ISSUE TITLE
All IDG aircraft fail to load, Error Code 0x247 Missmatch

### ISSUE THREAD

**Issue by tonghuix** [it0uchpods/IDG-A32X#132]
### Expected Behavior

Load normally without missmatch error warning.

### Current Behavior

Fail to load, and shown error warning with Error Code 0x247 Missmatch

### Possible Solution

Not yet...

### Steps to Reproduce

1. Git clone or pull latest master branch version
2. FG 2017.4 (next branch), set proper for aircraft addons
3. Run with ANY IDG's aircraft

**Comment by it0uchpods** [comment]
Hi @tonghuix 
Please be advised that we do not support these builds of FlightGear. On 2017.3.1, I get a welcome message, no errors. Maybe tell me your airport/rw/etc. 

0x247 is a failure of loading nasal system libraries. Try to reinstall the aircraft, other than that, we don't provide support to 2017.4.0, or 2018.1.0. Once 2018.1 is released

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
![image](https://user-images.githubusercontent.com/25598604/35900214-bdf2c1a4-0b9e-11e8-8149-d9c9eea91c2d.png)
Revision 4315 works fine on a tester's 2017.4.0.

Josh

**Comment by tonghuix** [comment]
It seems works perfect at this time. I can't reproduce the bug any more and don't know why.

**Comment by it0uchpods** [comment]
Alright!

Josh
