### ISSUE TITLE
Checklist texture not shown under linux

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#136]
### Expected Behavior
texture is shown

### Current Behavior
texture not shown

### Possible Solution
check naming

### Steps to Reproduce
1. start fg on linux

When do you finaly get ridg of always doing this kind of mistakes????

**Comment by it0uchpods** [comment]
I never saw this issue because the GitHub bot in Slack was down -- apologies!

Fixed as of Revision 4316.

Kind Regards,
Josh
