### ISSUE TITLE
Feature request: Add hitbox and make walker more realistic

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#143]
Add a hitbox to the stairs and the aircraft floor and make the start position for the walker outside the cockpit door.

As an extra, when i walker view, a click on the cockpit door disables the walker and you're back in the cockpit again.

**Comment by it0uchpods** [comment]
No plans to modify the walker as if now.

Sorry.
Josh

**Comment by merspieler** [comment]
Would you mind if i do?
