### ISSUE TITLE
no ATIS received

### ISSUE THREAD

**Issue by bob755** [it0uchpods/IDG-A32X#144]
No audible or text ATIS is received when COM1 or COM2 is tuned  to the ATIS frequency of the local airport.
Tested at LFPO. WIth a Cessna 172.  ATIS is received

### Expected Behavior
ATIS should be received when radio is tune to the local ATIS freqeuncy

### Current Behavior
No audio or text ATIS received

### Steps to Reproduce
1. Start FG at airport with ATIS (eg. LFPO)
2. Power up aircraft (ready to taxi)
3. Tune COM1 or COM2 to local airport ATIS frequiency
4.

**Comment by tonghuix** [comment]
And have you power on the plane?

**Comment by merspieler** [comment]
@tonghuix lol... read step 2 of his steps to reproduce

**Comment by tonghuix** [comment]
Sorry for that..

I tested again, it is confirmed that can not hear ATIS audio. And the audio panel is not clickable.

![fgfs-screen-409](https://user-images.githubusercontent.com/423703/37658816-5d507bbe-2c89-11e8-8ca5-512f9a417537.png)

**Comment by merspieler** [comment]
It's known, that the RMP and the ACP are not functional. They'll come when the remodeling is done.

Press <F12> to get the build in radio pannel and try again ;-)

**Comment by tonghuix** [comment]
I used the build-in radio panel to tune frequency, but where to tune audio volume?

**Comment by merspieler** [comment]
'Files'->'Sound Configuration'

**Comment by tonghuix** [comment]
Still can not hear, 2018.2.

**Comment by merspieler** [comment]
then @legoboyvdlp please label as confirmed

**Comment by legoboyvdlp** [comment]
@merspieler I have not confirmed this. I have never experienced this 😕

**Comment by legoboyvdlp** [comment]
`<comm-radio>
    <name>comm</name>
    <number>0</number>
  </comm-radio>

  <comm-radio>
    <name>comm</name>
    <number>1</number>
  </comm-radio>`

soloution suggested by PINTO for my reference when fixing

**Comment by merspieler** [comment]
> I have not confirmed this. I have never experienced this

Me nigther... I request ATIS from ATC of fly without it... so I've never used it.

**Comment by legoboyvdlp** [comment]
Fixed in 25fb1ae4
