### ISSUE TITLE
Feature request: Adding Rembrant compatibility

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#145]
Add compatibility for the use with Rembrant... don't get me wrong, I don't want to get ridg of ALS, just add the compatibility.

**Comment by legoboyvdlp** [comment]
I'm really sorry, it seems like most times you come up with a good idea, the answer is no. But, in this case, Rembrandt is extremely inefficient (calculates shadows 50km away at night, for instance). Also, it has troubles with glass cockpit displays and  transparent objects. It also uses a load of memory. 

Honestly, Rembrandt is great: it is a good way to add shadows and lights to ghe scene. But when ALS can do the same, as well as looking so much better, without the performance impact, don't you agree we should focus on ALS? ;)

This is not an outright denial: like on the MD11, I actually do plan to at least add Rembrandt lighting. But that will be much closer to v1.0: the FMGC is a priority right now, and it might be closer than you think... :stuck_out_tongue:

**Comment by legoboyvdlp** [comment]
At minimum, we will ensure the model does not cause artifacts with Rembrandt.

**Comment by legoboyvdlp** [comment]
Tbh all that needs done is just to add the lights. So it isn't that much work.

**Comment by merspieler** [comment]
> But when ALS can do the same, as well as looking so much better

um... ALS looks just surrealistic without shadows... as well... on the "shadow" side you can't see details with the same color (cool at the antena on the bottom, facing the sun) not lit == not lit... no matter where

**Comment by legoboyvdlp** [comment]
I don't think it is inefficient, having looked at the code, I know it is unfortunately inefficient. 

Plus, ALS can have shadows, and we are going to try and add them :)

**Comment by merspieler** [comment]
Well, maybe for the plane, but how about the scenery?

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/37705056-a81ed7da-2cf2-11e8-8e97-630337742dbb.png)

I'll bring it up with Thorsten about adding shadows to the other objects in the scene.

**Comment by merspieler** [comment]
I know the image and that trees can have shadows, but what about other buildings? Never seen shdows there... aswell... shadows are only cast on the ground (same goes for light) and not on any objects, that are in the way.

**Comment by legoboyvdlp** [comment]
@merspieler 

> I think if it's shadows which get you all excited about FG, you should use Rembrandt, as simple as that. 

> If, on the other hand, you're interested in a general balance of realistic visuals, you're better off with ALS which uses the performance saved on not doing shadows for other elements in the scene.

**Comment by merspieler** [comment]
If stereoscopic view or rembrant halfs my fps doesn't matters :P

**Comment by merspieler** [comment]
Even to the summer solstice (Sun is at it's highest point in the sky of the year) the Empire State Building (total height 443.2 m) still casts a shadow of ~138m
https://www.suncalc.org/#/40.7484,-73.9857,13/2017.06.22/13:00/443.2/0

**Comment by merspieler** [comment]
An not to forget to see, that the pyramid of giese has actually 8 sides

**Comment by merspieler** [comment]
And in the end, it's up to the user what to use, but you should give them the possibility to choose...
Either fly with a unrealistic plane or a unrealistic scenery.

**Comment by it0uchpods** [comment]
There will be no Rembrandt support in the aircraft. We have chosen in favor of ALS.

Kind Regards,
Josh
