### ISSUE TITLE
Ditching pb can't be turned off

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#15]
### Expected Behavior
Ditching pb can be turned off

### Current Behavior
Ditching pb stays on

### Steps to Reproduce
1. Switch Ditching on
2. Try to switch it of

### Info:
The ditching pb is part of the deicing procedure to seal the a/c beforehand.

**Comment by it0uchpods** [comment]
I didn't know that. 
Will fix it once home.

Josh
