### ISSUE TITLE
MCDU Flightplan

### ISSUE THREAD

**Issue by wopl** [it0uchpods/IDG-A32X#17]
As I cannot find proper docs, this is more a question than a bug report

### Expected Behavior
After entering "init" values into MCDU I expect to open the "flightplan" screen.

### Current Behavior
my screen stays black

Is this feature not implemented yet? Any plans of when getting flightplans working?

**Comment by it0uchpods** [comment]
I'm currently still stick with medical issues, but I have started recovering. This is first on my list once I am better.

TL;DR: Coming soon(tm)

**Comment by wopl** [comment]
hope you recover soon. And thanks for the phantastic A320 so far. One more wish: cockpit illumination for nightflights highly desired. Programming the MCDU in the dark is more than a challenge :-)

**Comment by ACH1980** [comment]
Just a short question on this:
I've seen, that you're working on the FMGS - especially on the F-PLN Page. I just want to know the actual state and when you expect, that this is ready (I know you can't give a guarantee, but this is not what I want to ask, I just want to ask you what do you expect)...

**Comment by Octal450** [comment]
Hi @ACH1980 and thanks for the interest.

The FMGS is stalled because we are going to rewrite the entire airplane. There is lots of legacy and inefficient code (which I realized when I started doing the FMGS). We are working on something called "IntegratedSystems" which combines extreme detail, with much better performance on frames, as well as other improvements. 

After the rewrite, work will resume.

Kind Regards,
Josh

**Comment by spectral-ai** [comment]
Hi @Octal450 
Many thanks for this wonderful aircraft!
Is there any news on this particular issue? I understand, that MCDU implementation has been discontinued altogether, is that correct? If you say, that you are rewriting the entire airplane: is there a related github project?

**Comment by Octal450** [comment]
Discontinued - no!
we are rewriting the airplane because it is missing alot of detail - this became apparent as we started work on the FMGS.
After the systems is rewritten (in this plane itself), we will continue on the FMGS.

Kind Regards,
Josh

**Comment by spectral-ai** [comment]
Brilliant, thanks for the swift response! Looking forward to the full featured FMGS!
Kind Regards
Jan
