### ISSUE TITLE
Landing gear is not shown over mp

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#18]
### Expected Behavior
Gear is shown as usual

### Current Behavior
Gear doesn't show up

### Steps to Reproduce
1. Start with the `320-214` (`A320-200-CFM`)
2. Let a friend look at it.

**Note**: this isn't 100% reproduceable... watch ATCjomos videos to see the problem.

**Comment by it0uchpods** [comment]
I cannot reproduce this! and I DO NOT know why this happens, but it does somehow... Don't understand.

Josh

**Comment by it0uchpods** [comment]
Not caused by the plane. Gear props are automatically fowarded.

Josh

**Comment by merspieler** [comment]
Just found out, that the Citation-II has the same bug...

> This conversation is non-productive, sorry you don't agree to the way we've decided to do our work.
How can I agree, if I don't even know the exact way?

**Comment by it0uchpods** [comment]
I repeat, 

> Not caused by the plane. Gear props are automatically fowarded.

Watch it with the unproductive talk. This is not the place for it.
