### ISSUE TITLE
Bad calc of the Ground Speed / TAS

### ISSUE THREAD

**Issue by BAWV12** [it0uchpods/IDG-A32X#19]
Ground speed on ND is everytime same as TAS, no matters of the wind direction and speed.
Example :
GS 430 kts, TAS 430 kts, tailwind 25 kts. 
In this case GS should be 455 kts.

Fresh observation :
Probably, correct is GS, not TAS, because GS was changed after wind direction change.

**Comment by BAWV12** [comment]
Next example :
GS 230 kts, headwind 25 kts, TAS 230 kts - something is bad. But GS or TAS ?
Standard ISA calculator from http://www.newbyte.co.il/calculator.php :
CAS 200 kts
TAS 250 kts
When I add headwind to GS, result for TAS is 255 kts, and this is close to calculated 250 kts for TAS.

**Comment by BAWV12** [comment]
Next example :
I used standard ISA calculator from http://www.newbyte.co.il/calculator.php :
FL210
CAS 300 kts
TAS on ND 440 kts
GS on ND 440 kts, tailwind 35 kts

By calculator, TAS should be 406 kts.

**Comment by it0uchpods** [comment]
Yes, I've been looking into this recently.

Josh

**Comment by BAWV12** [comment]
Again another nice example with very strong 90 kts tailwind :
FL310
CAS 300 kts
GS on ND 568 kts
TAS on ND 568 kts, by calculator should be 473 kts, difference GS-TAS is tailwind speed 

https://s31.postimg.cc/bmqtq06ff/fgfs-screen-012.png

**Comment by BAWV12** [comment]
Tested, now GS/TAS are OK. Thank You for quick fix.

**Comment by it0uchpods** [comment]
Thank you for reporting it!

Kind Regards,
Josh
