### ISSUE TITLE
Engine start is not possible

### ISSUE THREAD

**Issue by xomasz** [it0uchpods/IDG-A32X#20]
### Expected Behavior
When I click on the "Ready for takeoff" button in the launcher menu, the engines should start and stay on.

### Current Behavior
When I click on the "Ready for takeoff" button in the launcher menu, the engines start for a moment, but after a few seconds, both engines level down and finally show the "XX" on both sides in the engine menu. Short time after this, the aircraft completely loose electrical power without APU/EXTPWR.
The same thing happens when I try to start the engines manually.
It's nearly the same thing on the latest version of the IDG-A33X, but there only the ENG1 shuts down, the ENG2 stays on (but as I wrote: On IDG-A32X, both engines shut off).

### Possible Solution
-/-

### Steps to Reproduce
1. Choose any aircraft from the latest version of the IDG-A32X series and run it in FlightGear.
2. In the launcher menu, choose the preset "Ready for Takeoff" and see what happens.
3. You can try the same thing with starting the engines manually, but - as I wrote - it will happen the same thing.

**Comment by it0uchpods** [comment]
Good day @xomasz 
Sadly I can not reproduce this. Can you check for console errors?

![image](https://user-images.githubusercontent.com/25598604/39399127-527afb9e-4ae6-11e8-8a3f-4dc6c69efdf5.png)

Do you have fuel?

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Hi,
Can you tell me what is inside revision.txt? I want to see if I can figure out what changed.

Of course. Glad to help.

Josh

**Comment by it0uchpods** [comment]
Thank you! Please give me some time to look at all the differences between the two versions and I'll get back to you. Are you comfortable editing some files? If I can pinpoint exactly what code is the problem perhaps we can find a solution!

Can I also know your operating system, and where you got FlightGear from? (built from source, ubuntu repo, etc)

Josh

**Comment by xomasz** [comment]
Sounds great!
Of course, if you write me what I have to do, I can edit things :)
My operating system is macOS (Version 10.13.4). I got FG from SourceForge in a .dmg-package (so I just had to extract the app from the dmg)

**Comment by it0uchpods** [comment]
Alright. I'll get back to you later today or tomorrow morning.

Thank you.
Josh

**Comment by it0uchpods** [comment]
Hi,
My first idea: Can you open Nasal/libraries.nas and delete lines: 242-247?

Does it work now?

Josh

**Comment by xomasz** [comment]
There are exactly 15000 pounds in the left wing pump and 15000 pounds in the right wing pump - there's no other fuel.
When I go to /engine, there is no engine[0], so I checked the engine value when the engine fails - state of "engine" stays at 0.
The value of the second item you asked for stays at "9 (double)" .

**Comment by it0uchpods** [comment]
Sorry. FG calls engine[0] just engine. Monitor it while it attempts to load panel state. Does "state" inside "engine" go to 1, 2, or 3 while starting?

0 = Fuel off
1 = Cranking
2 = Ignition and spooling up
3 = Engine Ready

I mean, not the pumps, but the fuel tanks labeled "Engine 1 Pipes" and "Engine 2 Pipes". They should have 8-10 in them.

OK, it stays at 9, which means the pipes aren't getting refilled by the tanks properly.

Could you make a video, showing the Fuel and Payload Settings while it starts? I'd like to monitor exactly what the tanks are doing.

Don't use the plane with those code removed. The engines are running, but the systems won't be controlled properly.

Best,
Josh

**Comment by it0uchpods** [comment]
Hello,
So sorry that I did not get back to you. I've started healing from my medical issues, and thus have been focusing on schoolwork. Hope you understand.

I will look into this again this afternoon when I am home.

Thank you,
Josh

**Comment by xomasz** [comment]
No problem, the most important thing is to become healthy, so take as much time as you need :)

**Comment by it0uchpods** [comment]
Hi @xomasz I am confused.
The engines don't shutdown in your video.

Josh

**Comment by xomasz** [comment]
Yeah, that's right. Sorry, maybe it wasn't that clear to understand in my previous message:
I decided to disable the fuel freeze option before I made this video, and the result was that both engines were able to start (as you can see). The only abnormal thing were the engine 1 fuel value which decreases way faster than the engine 2 fuel value.
But when I enable the fuel freeze option, the engine 1 spools down and ends up after a pretty short time (I would make a video of it also, but I'm unsure if it's necessary because you can't see anything changing in the Fuel And Payload menu when fuel freeze is on.

**Comment by xomasz** [comment]
Ahh okay, that makes sense :)
Yes, without the fuel freeze setting, the A330 works correctly and without any problems (the engine 1 fuel decreases faster than the engine 2 fuel, but just a little bit, I think that's not a big deal, is it?)

**Comment by it0uchpods** [comment]
^^^
That is very weird.
I am not sure what is going on there. Are you comfortable with something like Join.me for a screen sharing (not remote control) session? Without reproducing I don't understand what is going on.

Josh

**Comment by xomasz** [comment]
Sorry, I have to revise what I wrote: I wanted to tried it out for another time before we make a screen sharing, but now, it stays at the same line, exactly how it should work.
I had this bug with the fast decreasing only one time, but I thought it's a permanent bug...probably something simply went wrong when I had this problem for the first time...
Sorry for the confusion and thanks for help me! :)

**Comment by it0uchpods** [comment]
No problem whatsoever. Glad it is now working for you!

Enjoy!
Josh
