### ISSUE TITLE
MP aircraft have same lights on as own

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#22]
### Expected Behavior
The lights which the MP has on should be on

### Current Behavior
The lights I have are on on the Mp aircraft
Or all are off, if I'm near by with a different aircraft

### Steps to Reproduce
1. Start a MP session near to another IDG-A32X
2. Play with the lights and observe the other plane. (Your changes apply on your and the MP A/C)
3. Ask the other pilot to play with the lights and observer. (You can't see any changes)

**Comment by it0uchpods** [comment]
Not a bug.

We chose to omit them for now, because there were not enough multiplayer props. We will later re-examine if we can use the fake engine "cheat" to get around it, but not until all the lighting is complete.

Josh
