### ISSUE TITLE
Feature request: AP disconnect key

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#23]
Add a key that behaves like the red AP disconnect button on the side stick.

**Comment by it0uchpods** [comment]
Easy enough, do you have a key suggestion?

Will also have to improve the AP disc sound logic.

Josh

**Comment by merspieler** [comment]
i have no clue which keys are already in use... (by the a320 and fg) 

as you mention the sound... iirc on ap disc the sound goes on until the ap disc is pressed again...

**Comment by it0uchpods** [comment]
Yes, that is what I did mean. :smile: 

Josh

**Comment by merspieler** [comment]
That's the key?
