### ISSUE TITLE
Bug: Spoiler moved to full position on landing

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#26]
### Expected Behavior
On landing with spoilers armed, the spoiler lever stays in the armed position.

### Current Behavior
The lever moves to the full position

### Steps to Reproduce
1. Fly an approach with armed spoilers
2. After the landing take a look at the spoiler lever

Same applies on abort TO

**Comment by it0uchpods** [comment]
This doesn't happen for me. The lever moves to the full position. 

The animation is based on the same property that the autospeedbrake controller works on, therefore, if the speedbrakes deploy, then the lever must move.

Josh

**Comment by merspieler** [comment]
https://www.youtube.com/watch?v=U6R1nvgfIZQ&t=154
Look down (it's a 360° video)

**Comment by it0uchpods** [comment]
OK, never thought that! thanks.

**Comment by it0uchpods** [comment]
OK.
To be honest, the speedbrake code is legacy code that is largely unchanged since the first few versions, so I think I am going to completely rewrite it sometime soon. I'll address this when I do that.

Josh

**Comment by merspieler** [comment]
Well I didn't dig for the mistake... I've just never heared of a automatically control in an Aibus cockpit except the trim wheel. I had to look it up my self in first place.

**Comment by legoboyvdlp** [comment]
Good catch, thanks.
I actually never noticed, I never looked down till I disarmed speedbrakes on exit. I guess when the speedbrakes were not extended then the lever went back to armed

**Comment by it0uchpods** [comment]
Ahh, so it's not only me who missed it! Good to know :wink:

**Comment by merspieler** [comment]
Any update on this?

**Comment by it0uchpods** [comment]
No. Be patient. I'm busy.

**Comment by it0uchpods** [comment]
Fixed in the in-dev new spoiler system.
