### ISSUE TITLE
Bug: Parking break animation inverted

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#28]
### Expected Behavior
Handle "looks" forwards when not set and right when set.

### Current Behavior
Handle "looks" right when not set and forwards when set.

Exists since 77db135f3867701303dca40b147755a02e7cbaf5

### Steps to Reproduce
1. Look at the parking break handle.
2. Toggle parking break.
3. To check if parking break is set applie thrust or look if GPU can be connected

**Comment by it0uchpods** [comment]
Fixed by Thorsten as of 29f0f60

J
