### ISSUE TITLE
Landinglight move with view

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#3]
### Expected Behavior
Lights on the ground point always to the same spot

### Current Behavior
They move if the view is moved

### Steps to Reproduce
1. Start at night
2. Turn LDG LT on
3. Turn view around and watch the casted light

**Comment by merspieler** [comment]
it moves in cockpit view aswell

**Comment by BAWV12** [comment]
Default C172p has working landing lights in external view. I adopted it for my Concorde and working good. Check the file https://github.com/BAWV12/Concorde/blob/master/Nasal/light-manager.nas

**Comment by it0uchpods** [comment]
@legoboyvdlp that's not true, it can be done. PLease check BAWV12s integration

**Comment by merspieler** [comment]
Any update on this?

**Comment by it0uchpods** [comment]
@legoboyvdlp

**Comment by legoboyvdlp** [comment]
?

**Comment by legoboyvdlp** [comment]
How's this?
![image](https://user-images.githubusercontent.com/10434911/43768761-0214436a-9a30-11e8-8652-8d3e9a77e641.png)

@merspieler

**Comment by merspieler** [comment]
If it down't move, that's a step forward... and then maybe check the look of the casted light with rl pics...

**Comment by legoboyvdlp** [comment]
Closed with af9eee - we can improve the lights later, but the main issue here is closed.

**Comment by merspieler** [comment]
For the outside, it looks better now but the problem still excists when in the cockpit (which annoys me more than the outside view):  
[![fgfs-screen-031.png](https://s20.postimg.cc/stblxxnd9/fgfs-screen-031.png)](https://postimg.cc/image/52c8ftn61/)

... Btw... the light seems to flicker on cam movement with the current solution.

**Comment by it0uchpods** [comment]
I didn't have that issue, it worked in the cockpit fine for me... @legoboyvdlp confirm please?
The flicker I think can't be avoided quite yet.

**Comment by merspieler** [comment]
Do you move the view by mouse or by joystick?

**Comment by legoboyvdlp** [comment]
Ah ok... I've never actually seen that before.

Well, in that case I'd say the best thing to do is simply remove the ALS secondary lights which move with the view and don't work outside and use the new lights not only outside but inside. It should look pretty much the same.

**Comment by merspieler** [comment]
the result is the pic is done with the hat on my joystick... maybe that's the problem(i saw else where that there's a difference between looking around with the mouse vs with the js)

**Comment by legoboyvdlp** [comment]
Right. I'll make a new commit shortly, can you test then? Thanks.

**Comment by merspieler** [comment]
sure

**Comment by legoboyvdlp** [comment]
Thanks!

**Comment by legoboyvdlp** [comment]
If you would like me to improve the look of the light on the runway (positioning) it would help if you send images here? Or if not, to legoboyvdlpATgmailDOTcom. :wink:

**Comment by merspieler** [comment]
I've found [this](https://www.youtube.com/watch?v=GeeDVDo1VpE) video, might not me the best POV tho.

TAXI LT comes on ~0:30
LDG LT comes on ~1:40

I'll keep on searching
