### ISSUE TITLE
Loading of V1 sound produceds lag

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#30]
### Expected Behavior
Loading of sounds should not create lag

### Current Behavior
Loading of the V1 callout sound (and maybe others) takes sometime a bit too long, creating a lag

### Possible Solution
Playing each sound at startup with 0 volume to load them.

### Steps to Reproduce
1. Take off in a session where you haven't took off before
2. From time to time (maybe about 1/10th) it lags before the V1 callout comes

**Comment by it0uchpods** [comment]
Thanks for reporting.

**Comment by merspieler** [comment]
NOT FIXED, PLEASE REOPEN

**Comment by it0uchpods** [comment]
Cannot reproduce it anymore.

**Comment by merspieler** [comment]
if i just look at the diff of the commit  8f1e5fd that closed this issue, i can't see any fix to this...

all i see is a change of the .wav file but nothing related to its loading

**Comment by it0uchpods** [comment]
It was poorly compressed, I recompressed it with audacity.

**Comment by merspieler** [comment]
it still happens...

**Comment by it0uchpods** [comment]
Well, not for me. You are welcome to investigate yourself.

**Comment by merspieler** [comment]
i've downloaded both versions and they even have the very same size:

```
$ ls -l
total 64
-rw-r--r-- 1 user user 31244 Aug 13 21:37 V1-old.wav
-rw-r--r-- 1 user usern 31244 Aug 13 21:37 V1.wav
```

**Comment by it0uchpods** [comment]
Don't know to tell you, after I did this, it stopped happening. As I said, you are welcome to propose a fix yourself.

**Comment by merspieler** [comment]
ok. where's the soundcontroling file?

**Comment by it0uchpods** [comment]
A320-common-sound.xml

**Comment by merspieler** [comment]
just FYI: .wav is a uncompressed file format... the compression you've applied on the sound is a sound compression aka [Dynamic Range Compression](https://en.wikipedia.org/wiki/Dynamic_range_compression)

The only way to reduce size of .wav files is to reduce the sample rate or the size of a sample. I've did the fromer method with the file from the PR.

**Comment by it0uchpods** [comment]
Ahh ok, I am not that great with audio, so I probably used the wrong words, but it did stop for me whatever audacity did, odd.

Thanks for fixing it m.

J
