### ISSUE TITLE
Flight Route line on ND disappeard

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#32]
### Expected Behavior
Flightplan line kept shown

### Current Behavior
Line disappears sometimes... I can't reproduce it.
![](https://s20.postimg.cc/5k1vf5f71/fgfs-screen-002.png)

### Steps to Reproduce
I'm not really sure how to reproduce it.

**Comment by it0uchpods** [comment]
Neither can I, so sadly I can't look into it. :(

**Comment by merspieler** [comment]
seems to be #7 ... weather related
