### ISSUE TITLE
G HYD miracly powered

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#37]
Setup: 

Engine 2 is running and powers the yellow system with 3000PSI and PTU pressures green as well with 3000PSI.  
If now the Yellow HYD Leak failure in the menu is enabled, the yellow pressure drops to 0 as expected

### Expected Behavior
Green pressure drops to 0 as well since the yellow system can't power the green one via the put anymore.

### Current Behavior
Green pressure stays 3000 PSI

### Steps to Reproduce
1. Start engine 2 and wait a bit until hyd pressure is in both systems at ~3000PSI
2. Enable the Yellow HYD leak in the System Failures menu
3. Check the pressures

**Comment by it0uchpods** [comment]
Oops ;)

**Comment by it0uchpods** [comment]
Thanks for the report!

Josh

**Comment by merspieler** [comment]
You've solved that single problem... there are many similar unfixed :D 
![fgfs-screen-054](https://user-images.githubusercontent.com/29063255/45585702-168c8a00-b8e9-11e8-8ed5-a1fcbdd0e76a.png)

**Comment by legoboyvdlp** [comment]
@merspieler Hey,
I think I fixed that last night, maybe pull again from dev?

**Comment by it0uchpods** [comment]
Can you please make a new issue for that, if it still exists? Please test it first on master, also.

**Comment by it0uchpods** [comment]
@merspieler I fixed the engine 2 not going to off state, so would you please re-test and see if the above scenario exists?
