### ISSUE TITLE
AP can be enabled imedeatly after take off

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#38]
### Expected Behavior
AP can be enabled starting at a altitude agl (300ft iirc, better check)

### Current Behavior
AP can be enabled imediatly after take off (even below 50ft)

### Steps to Reproduce
1. Take off
2. As soon as a positive V/S is shown on the PFD, enable AP

**Comment by legoboyvdlp** [comment]
What is your reference for this @merspieler ? Thanks.

**Comment by it0uchpods** [comment]
OK, thanks lego.
The third point is already simulated IIRC. Second point, honestly I don't get it. Why would that be... I'll simulate it anyways. First point also, will do.

Josh

**Comment by legoboyvdlp** [comment]
The Airbus has some strange things 😂

**Comment by it0uchpods** [comment]
Hah yeah, like the APU Bleed PSI depending on the ADIRS? :D

**Comment by merspieler** [comment]
Wait... WHAT?
