### ISSUE TITLE
E/WD goes XX imideatly after ENG master OFF

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#39]
### Expected Behavior
The run down of the ENG is still observerable on the ECAM like seen in [this](https://www.youtube.com/watch?v=5YuXlu3Z7Bg&index=47&list=PLizmZUECr7f2sL0c6nruV60MWcqFp_vaw) video.

### Current Behavior
Goes instantly to XX display

### Steps to Reproduce
1. Shut down the engines and observe

### Note
The N1 indication on rundown has to be below a given value before the pilot should turn the beacon off.

**Comment by merspieler** [comment]
FCOM Vol1 1.70.20 P5 says, that the fadec stys powered for 5 min after ENG master off

**Comment by it0uchpods** [comment]
OK, didn't know that! Thanks, will simulate.
