### ISSUE TITLE
System: Large FPs causes large FPS drops (ex: 60 to 3FPS)

### ISSUE THREAD

**Issue by it0uchpods** [it0uchpods/IDG-A32X#4]
### Expected Behavior

Large FPs should not cause FPS drop

### Current Behavior

Huge Framerate drops with big flightplans

### Steps to Reproduce

1. Load up in any airport
2. Add many waypoints (10+)
3. Observe FPS
4.

**Comment by merspieler** [comment]
Can not confirm... no fps changes when flying with 33 waypoints compared to flying without fp

**Comment by it0uchpods** [comment]
Can no longer confirm either.
