### ISSUE TITLE
Left Display says ATT and HDG instead of Horizon and Heading

### ISSUE THREAD

**Issue by ErrorFlexXx** [it0uchpods/IDG-A32X#40]
Hello,

just a short question - maybe I have to press a button and missed it.

But if I startup the plane, the left display just says ATT in red and centered and HDG in Red on the bottom middle, where the heading output should be. Is this a bug or am I doing it wrong ? (If I set the 3 switches in the upper left on the overhead panel to ATT or NAV and wait for the alignment, the lights "ALIGN" are going off after some times, but the display remains unchanged.)

Screenshot:
![alt text](https://www2.pic-upload.de/img/35953946/Screeny.png "Screenshot")

**Comment by legoboyvdlp** [comment]
Is this after the last change? Perhaps I broke something.

**Comment by merspieler** [comment]
You have to set FROM/TO in the MCDU... have you done that?

**Comment by ErrorFlexXx** [comment]
Yes, I set it.

**Comment by legoboyvdlp** [comment]
Did you press ALIGN IRS ->?

**Comment by it0uchpods** [comment]
You also need to wait about 10 mins, or tick the ADIRS aligns instantly in Aircraft Config.

**Comment by ErrorFlexXx** [comment]
? Yes, I pressed it and nothing happened.

Then I switched the three IRS Switches on the overhead panel to off. Enabled ADIRS aligns instantly. Switched it to ALIGN again, then pressed IRS Align in the MCDU and then the screen shows me all the data.

So I've done the steps in the wrong order I think.
Many thanks for your help!

**Comment by legoboyvdlp** [comment]
No problem!

**Comment by it0uchpods** [comment]
Glad it's working! 
Enjoy the craft,
Josh

**Comment by legoboyvdlp** [comment]
By the way, if you use Atmospheric Light Scattering, performance will be better, and you will have working exterior lights ;)

**Comment by ErrorFlexXx** [comment]
I have to say thank you! 
For support in minutes from three different people
and that nice (and very detailed) model :D

=> Thank you! You're awsome!

**Comment by legoboyvdlp** [comment]
:)

**Comment by it0uchpods** [comment]
We are glad to hear that! Thanks slot!

Kind Regards,
Josh
