### ISSUE TITLE
ADF freq not displayed correct if NDB in range

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#43]
### Expected Behavior
The MCDU shows the ADF freq and, if in range, the ADF ID

### Current Behavior
If not in range, it works correct, if the NDB comes in range, there's some flickering between correct and described below.

If the NDB is in range, the MCDU shows nothing useful anymore. While the prop `/FMGC/internal/adf1-mcdu` shows the expected value in the format of `freq/id`, the mcdu shows just unrelated numbers.

### Steps to Reproduce
1. Start at EDDM, power up the plane.
2. Enter in the MCDU in the ADF1 `400` (NDB MSW)
3. Observe, that the field shows nothing useful.
4. Depart and observe the field while getting away from the NDB

**Comment by it0uchpods** [comment]
Fixed in 6dd3647
