### ISSUE TITLE
Contrails too bright at night

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#48]
### Expected Behavior
The contrails are as dim as the clouds are at night

### Current Behavior
They are almost completly white

### Steps to Reproduce
1. Fly at night and observe contrails

**Comment by Zaretto** [comment]
Use the scene rendering diffuse red color for the RGB in the particle start/end to fix this. Don't be tempted to use the diffuse R,G,B as Thorsten said you should only use the red (something to do with the physics of the light scattering).
e.g.
`       <particle>
            <start>
                <color>
                    <red>
                        <expression>
                            <product>
                                <value>1.0</value>
                                <property>rendering/scene/diffuse/red</property>
                            </product>
                        </expression>
                    </red>
                    <green>
                        <expression>
                            <product>
                                <value>1.0</value>
                                <property>rendering/scene/diffuse/red</property>
                            </product>
                        </expression>
                    </green>
                    <blue>
                        <expression>
                            <product>
                                <value>1.0</value>
                                <property>rendering/scene/diffuse/red</property>
                            </product>
                        </expression>
                    </blue>
                    <alpha>
                        <value> 0.6 </value>
                    </alpha>
                </color>
                <size>
                    <value>2.5</value>
                </size>
            </start>

            <end>
                <color>
                    <red>
                        <expression>
                            <product>
                                <value>1.0</value>
                                <property>rendering/scene/diffuse/red</property>
                            </product>
                        </expression>
                    </red>
                    <green>
                        <expression>
                            <product>
                                <value>1.0</value>
                                <property>rendering/scene/diffuse/red</property>
                            </product>
                        </expression>
                    </green>
                    <blue>
                        <expression>
                            <product>
                                <value>1.0</value>
                                <property>rendering/scene/diffuse/red</property>
                            </product>
                        </expression>
                    </blue>
                    <alpha>
                        <value> 0.00000001</value>
                    </alpha>
                </color>
                <size>
                    <value>2.75</value>
                </size>
            </end>

            <life-sec>
                <value>20</value>
            </life-sec>

            <mass-kg>71.9</mass-kg>
            <radius-m>1</radius-m>
        </particle>`

**Comment by it0uchpods** [comment]
@legoboyvdlp , any update on this?

J

**Comment by legoboyvdlp** [comment]
I was meant to be doing this?

**Comment by legoboyvdlp** [comment]
Ok, I can do this in the morning. :+1:

**Comment by it0uchpods** [comment]
Yes.... you are the effects master :D

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/48636409-b25a7500-e9c2-11e8-9828-9b9f7e142617.png)

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/48636565-301e8080-e9c3-11e8-9da0-e9ac0df982ea.png)
