### ISSUE TITLE
Tail not visible at night with/without logo light

### ISSUE THREAD

**Issue by it0uchpods** [it0uchpods/IDG-A32X#49]
![image](https://user-images.githubusercontent.com/25598604/46249485-db657d00-c3f7-11e8-9b63-7dd460b2190d.png)

### Expected Behavior

Tail should be visible like fuselage is at night

### Current Behavior

Cannot see the tail

### Steps to Reproduce

1. Switch to night time
2. Observe tail with logo light on/off
3.
4.

**Comment by legoboyvdlp** [comment]
I looked again. It really should not do this. All I can think is maybe the logo lightmap is at fault

Anyway hopefully the new model fixes it

**Comment by it0uchpods** [comment]
OK fine.

**Comment by it0uchpods** [comment]
Closing this because it won't be fixed before the new 3D
