### ISSUE TITLE
Feature request: GPU connect if airport has GPUs available

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#5]
The GPU connects automatically on arrival/spawn at a parking possition if the airport supports GPUs.

If FG/TerraGear doesn't have this information, it would be possible to look up the objects whether there are GPUs placed near by.

**Comment by merspieler** [comment]
Why have you closed this?
Are you not interrested in this feature?

**Comment by it0uchpods** [comment]
Because we have a new way of dealing with this, and not only that, I have it in our Todo list so it's redundant to be here.

J

PS: I'm only answering this once, not every time you ask.

**Comment by merspieler** [comment]
New way?

Your todolist... Again this private stuff...
Is this an open or a closed project?

**Comment by it0uchpods** [comment]
The code is open source. I don't have to share what I plan to do.

J

**Comment by merspieler** [comment]
yeah... so that this shit with double or unnecesarily written code happens agaion...

what's the new way of dealing with this?

**Comment by it0uchpods** [comment]
You'll see

**Comment by merspieler** [comment]
will I?

**Comment by it0uchpods** [comment]
This conversation is non-productive, sorry you don't agree to the way we've decided to do our work.
