### ISSUE TITLE
Glideslope Callout on non visual approach

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#52]
I've been approaching GCLP which has no glideslope ils or anything else that could indicate altitue on approach.

### Expected Behavior
No glideslope callout

### Current Behavior
Glideslope callout

### Steps to Reproduce
1. Approach an airport without any vertical guidance but fly much too low (preferable over the sea to not trigger a terrain warning).

**Comment by legoboyvdlp** [comment]
That's the hardcoded GPWS system as far as I know. Post a ticket on sourceforge

**Comment by it0uchpods** [comment]
^^^

Yep. Only the altitude callouts are specific to the A3XX. Not our bug. Perhaps ask them for a specific inhibition to the GS callout that we can manipulate via the aircraft.

Josh
