### ISSUE TITLE
MCDU `.` isn't shown correct

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#6]
### Expected Behavior
The `.` is always displayed/removed on keypress

### Current Behavior
On some pages, the `.` dis/appreas when the following/preceeding char is added/removed.

### Steps to Reproduce
1. on INIT B enter block with something like `5.4` and observer the `.`
2. clear the line and observer again

**Comment by it0uchpods** [comment]
Also, ".0" has the same problem, the .0 don't show up till another thing is added/removed.

Kind Regards,
Josh

**Comment by merspieler** [comment]
Any update on this?

**Comment by it0uchpods** [comment]
No. Be patient. I'm busy.

**Comment by legoboyvdlp** [comment]
This is because only the integer is shown if it is something like 1.0

it won't show anything X.0, only shows X

to solve ensure scratchpad is always double (setDoubleValue)?

**Comment by merspieler** [comment]
how to write something like `1/UP0.3` into a double?

**Comment by it0uchpods** [comment]
Scratchpad is a string. I'll experiment with it later today.

**Comment by it0uchpods** [comment]
It was due to a hackCanvas bug we fixed a bit back.
Fixed in bf88b87 but I never noticed... lol

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
Excellent!
