### ISSUE TITLE
Acconfig: cockpit lighting

### ISSUE THREAD

**Issue by legoboyvdlp** [it0uchpods/IDG-A32X#64]
Cockpit lighting is not enabled by acconfig. When dome-light is merged this should be added.

**Comment by merspieler** [comment]
imo this should depend on time... during day, no dome light (or other lights) are needed...

and you should differ between the states...
like:
* Ready for eng start -> dome on
* Ready for taxi/to -> dome off

you don't want a bright cockpit at night when you need to see something outside.

**Comment by it0uchpods** [comment]
Not a bug
