### ISSUE TITLE
Red error after loading

### ISSUE THREAD

**Issue by munala** [it0uchpods/IDG-A32X#69]
I downloaded the latest update and started with the A320-232 and got an error saying `Something happened and this plane has been disabled`. It used to work fine until I downloaded the current latest version.

### Expected Behavior
I should be able to control the plane after the simulator finishes loading.

### Current Behavior
I get an error after loading.
### Possible Solution
I don't know. For now I can revert to an earlier version.

### Steps to Reproduce
1. Open the launcher (Macos)
2. Go to aircraft panel and select Airbus A320-232 (IAE V2527-A5)
3. Go to location panel and select KSFO parking E65
4. Click `Fly!`
5. Wait for it to finish loading then the error will be displayed

**Comment by legoboyvdlp** [comment]
Hello,
by current latest version do you mean 2018.3 or 2018.4 (development version)?

Also,
try going to an airport in another hemisphere - i.e. for you, maybe in south america, as sometimes flightgear does strange things like that.

**Comment by munala** [comment]
@legoboyvdlp I meant the latest version of the aircraft. I have flightgear 2018.3 and the aircraft has been working excellently until I downloaded the latest version of the aircraft, 6 hours ago.

**Comment by munala** [comment]
@legoboyvdlp I meant the latest version of the aircraft, I downloaded 6 hours ago. I have flightgear 2018.3 and I had not experienced any problems prior to today.
<img width="1680" alt="screenshot 2018-12-21 at 18 56 50" src="https://user-images.githubusercontent.com/22608948/50353275-c6147080-0558-11e9-98be-186c9e437d28.png">

**Comment by it0uchpods** [comment]
Hello,
There is a bizarre issues with FG that causes this to happen after installing a new version of FG. We do not know why this happened. Please try loading in at an airport at least 100nm away, if it works there, try going back to here and it should work.

Kind Regards,
Josh

**Comment by munala** [comment]
@it0uchpods I reverted to an older version of the aircraft I downloaded last week. Once I'm done with my current flight I'll try your suggestions.

**Comment by it0uchpods** [comment]
Ok. Please let me know if it continues to be problematic.

Josh

**Comment by it0uchpods** [comment]
I cannot reproduce this at all. I did not change the code that catches these errors and disables the plane for a while now. Can you please send your fgfs.log from $FG_HOME when this happens?

Josh

**Comment by munala** [comment]
@it0uchpods I completed a flight with the previous version of the aircraft. I then restored the newer version to try and reproduce the problem and now the problem is gone. That's weird but I'm glad its gone. Thanks for the help. I'll close the issue now. I'll let you know if I encounter the issue again.

**Comment by it0uchpods** [comment]
Great, thanks. @munala 

Enjoy the Airbus!

Kind Regards,
Josh
