### ISSUE TITLE
Displays show wierd things in low visibility

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#7]
### Expected Behavior
Displays show always the same, no matter of the weather

### Current Behavior
In ILS CAT 3 weather, visibility below 50m (starts earlyer at about 200-300m), some parts of the display are now shown (eg. VSI)

### Steps to Reproduce
1. Start in very low visibility and observe the displays

**Comment by it0uchpods** [comment]
FlightGear problem

**Comment by merspieler** [comment]
Ok, how about forewarding to the mailing list?

**Comment by it0uchpods** [comment]
When I have some time (very busy recently), I'll address this further It isn't really urgent, so it's not high on my priority list.
