### ISSUE TITLE
FG initialization does not complete with code 0x223 and preposterous configuration reason

### ISSUE THREAD

**Issue by jaypeeds** [it0uchpods/IDG-A32X#73]
This is about a very first installation of Flightgear 2018.3.1 on a new machine that never had any previous setup of it.
The software is behaving as expected with provided Aircraft (Cessna) and my custom location (LFMN airport)
Now the IDG-32X family folder is downloaded, Flightgear is re-started and all IDG-A32X models are properly listed in the pre-flight dialog where they can be selected. 

Machine configuration: MacMini 2018, Mojave, 32 GB RAM, 1TB SSD, 1Gb Ethernet.

### Expected Behavior
Startup completes and the aircraft is ready to fly, with cold engines, at parking position.

### Current Behavior
Startup does not complete at the point sound starts for about 1/2 second, the sound of a switch being toggled, then falls back on default "Welcome aboard" message with guidance for tutorials.

On screen, a red dialog is displayed:
Error code 0x223
Reason: Preposterous configuration detected for initialization. Check your position or scenery.
<img width="1005" alt="capture d ecran 2019-01-15 a 13 49 41" src="https://user-images.githubusercontent.com/4395141/51183024-5633a480-18d0-11e9-90cf-d602932b95f1.png">

### Possible Solution

None.

### Steps to Reproduce

1. Select first aircraft in IDG-A32X family, and first model within family in pre-flight dialog
2. Click Fly! Dark message box is reading "Please wait... Initializing..."

**Comment by legoboyvdlp** [comment]
Looks like you have no scenery (just water) below the aircraft which would cause that - check your scenery installation.

**Comment by jaypeeds** [comment]
I cannot confirm that the issue is the scenery as suggested by reason. 
- The default aircraft has no issue, the scenery is available, and the Cessna can take off.
- I changed the preference for the initial position at the start of a track, to make sure the position is not random. But I still experience the same issue with the same error code.

**Comment by jaypeeds** [comment]
It's night time... However, I found the log file and it suggests that the scenery data has negative elevation values:
'''
terrain:3:/Users/Shared/Hudson/MacRelease/simgear/simgear/scene/tgdb/ReaderWriterSTG.cxx:517:  Generating ocean tile: e000n40/e007n43/3072338
terrain:3:/Users/Shared/Hudson/MacRelease/simgear/simgear/scene/tgdb/ReaderWriterSTG.cxx:624:Loading tile 3072386.stg
terrain:3:/Users/Shared/Hudson/MacRelease/simgear/simgear/scene/tgdb/ReaderWriterSTG.cxx:517:  Generating ocean tile: e000n40/e007n44/3072386
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:1081:FGJSBsim::set_Altitude: -1.7621
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/flight.cxx:175:...initializing ground elevation to -1.8621ft...
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/flight.cxx:178:...initializing sea-level radius...
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/flight.cxx:181: lat = 43.6466 alt = -1.7621
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/flight.cxx:186:...initializing Euler angles...
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:1177:FGJSBsim::set_Euler_Angles: 0, 0.0074002, 0.778417
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/flight.cxx:195:...initializing velocities...
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:1093:FGJSBsim::set_V_calibrated_kts: 0
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/flight.cxx:233:End common FDM init
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:442:Ready to trim, terrain elevation is: -1.86016
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:1312:  Trim complete
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:466:  Initialized JSBSim with:
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:473:  Vn,Ve,Vd= 0, 0, -0 ft/s
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:495:  Bank Angle: -0.122393 deg
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:497:  Pitch Angle: 4.49807 deg
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:499:  True Heading: 44.5798 deg
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:501:  Latitude: 43.4544 deg
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:503:  Longitude: 7.20262 deg
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:505:  Altitude: 6.70092 feet
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:506:  loaded initial conditions
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:508:  set dt
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:510:Finished initializing JSBSim
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:513:FGControls::get_gear_down()= 1
nasal:5:/Users/Shared/Hudson/MacRelease/flightgear/src/Scripting/NasalSys.cxx:1202:Nasal runtime error: setprop() value is not string or number
nasal:5:/Users/Shared/Hudson/MacRelease/flightgear/src/Scripting/NasalSys.cxx:1214:  at /Applications/FlightGear.app/Contents/Resources/data/Aircraft/IDG-A32X/Nasal/FMGC-b.nas, line 603
nasal:5:/Users/Shared/Hudson/MacRelease/flightgear/src/Scripting/NasalSys.cxx:1218:  called from: /Applications/FlightGear.app/Contents/Resources/data/Aircraft/IDG-A32X/Nasal/FMGC-b.nas, line 426
nasal:5:/Users/Shared/Hudson/MacRelease/flightgear/src/Scripting/NasalSys.cxx:1218:  called from: /Applications/FlightGear.app/Contents/Resources/data/Nasal/globals.nas, line 119
nasal:5:/Users/Shared/Hudson/MacRelease/flightgear/src/Scripting/NasalSys.cxx:479:Mismatch: 0x223
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:567:0: GEAR_CONTACT: 0 seconds: NOSE_1 1
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:567:1: GEAR_CONTACT: 0 seconds: BOTTOM_1 1
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:567:2: GEAR_CONTACT: 0 seconds: BOTTOM_2 1
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:567:3: GEAR_CONTACT: 0 seconds: ENG_1 1
flight:3:/Users/Shared/Hudson/MacRelease/flightgear/src/FDM/JSBSim/JSBSim.cxx:567:4: GEAR_CONTACT: 0 seconds: ENG_2 1
view:3:/Users/Shared/Hudson/MacRelease/flightgear/src/Viewer/splash.cxx:686:Splash screen progress 

'''

**Comment by legoboyvdlp** [comment]
That again suggests it is a problem with scenery, not the IDG-A32X. 
(does the fact that you do not see a runway when you choose to start at a runway also confirm that?)

You can set a different time of day in the launcher or in the menu (toggled with F10) - should be under Environment.

Again, we need a screenshot to be sure.

**Comment by it0uchpods** [comment]
![image](https://user-images.githubusercontent.com/25598604/51206998-8a5e9380-18d7-11e9-9b29-24394c5371cb.png)

Sorry, cannot reproduce. Regardless, this is a SCENERY problem, not the aircraft. This screen is expected to appear when something TERRIBLE happens during the initialization, in this case, lack of scenery causing systems initialization to fail.

Kind Regards,
Josh
