### ISSUE TITLE
System doesn't recover from power loss in mid air

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#73]
### Expected Behavior
When the power is back the Computers should work as usual after some time.
System should return to normal law when computers has started.
All displays should show information again.

### Current Behavior
ELAC, FAC and SEC stay off(or faulty... if so, no lights on the ohp are illuminated).
System stays in direct law.
F/O PFD, both ND and lower ECAM displays stay black.

### Steps to Reproduce
1. In flight make sure the APU is off
2. Switch GEN1 and GEN2 off (system goes into mechanical law)
3. After few seconds switch them on again (system should return to direct law and when ELAC, FAC and SEC have started, return to normal law. The displays should show again normal information).

**Comment by it0uchpods** [comment]
Hi,
Thanks you for reporting. I've confirmed the issue with power loss, and displays and flight computers not coming back, but the FBW does not upgrade past direct law until the systems resets on the ground.

I will work on a solution tonight or tomorrow.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Fixing today

J

**Comment by it0uchpods** [comment]
Fixed.

Thanks and Kind Regards,
Josh
