### ISSUE TITLE
Landing Lights Still Broken

### ISSUE THREAD

**Issue by I-NICO** [it0uchpods/IDG-A32X#74]
In yesterday's update the Landing lights switches worked only if clicked with the mouse's center key/weel, in today's update they just don't work anymore.

Should be pretty easy for you to reproduce the behaviour!

**Comment by it0uchpods** [comment]
Hey I-NICO
I'll look at it, but please use the template. It makes it easier organize everything, even if it's really simple.

Kind Regards,
Josh

**Comment by Wecsje** [comment]
They indeed do not work, marked as bug.

**Comment by it0uchpods** [comment]
Hey I-NICO
I'll look at it, but please use the template. It makes it easier organize everything, even if it's really simple.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Issue confirmed, I used the wrong type of property while fixing the previous switch bug. Thanks for letting us know.

Revision 3029 fixes this.

Kind Regards,
Josh

**Comment by I-NICO** [comment]
Sorry about that, thanks for fixing it guys!

**Comment by it0uchpods** [comment]
No problem. Enjoy!

J
