### ISSUE TITLE
VOR needles missing

### ISSUE THREAD

**Issue by I-NICO** [it0uchpods/IDG-A32X#75]
Missing needles in VOR and LS mode.

### Expected Behavior
In VOR or LS mode, with VOR (1 and/or 2) switches on, the PFD should show a single line needle pointing the direction of VOR1 station and a double line needle pointing in VOR2 direction. Needles should turn and keep indicating the direction of the radio stations in relation to the aircraft position.

### Current Behavior
With both the VOR switches on PFD only shows alignment indicator, DME1 at the bottom L corner and DME2 at the bottom R corner.

### Steps to Reproduce
Just tune in your VOR1/VOR2 frequencies, PFD in VOR mode, VOR/ADF switches both on VOR.

**Comment by Wecsje** [comment]
Hi, we are aware of this bug. We will probably not be fixing it any time soon, but I've added it to the to-do list.

Regards,

Charlie (Wecsje)

**Comment by I-NICO** [comment]
I flagged this bug and another one on the forum few weeks ago, reporting them here again so that they don't get lost.
Without the needles it's nearly impossible to perform a DME, unless you don't want to set a new radial every 10 deegres!

Thanks,
Nico

**Comment by Wecsje** [comment]
We know this can be a big problem, but we have tried fixing it many times. I will see if I can bump it up on the agenda, but we are currently also very busy with other parts of the development.

Regards,

Charlie (Wecsje)

**Comment by it0uchpods** [comment]
Okay, I've done some checking.
By PFD do you mean ND?

I will fix it very soon. Keep your eye on the projects page.

Kind Regards,
Josh

**Comment by I-NICO** [comment]
Yup, sorry, navigation display.

Thanks for the effort guys, this plane is going better and better!!!

**Comment by it0uchpods** [comment]
No problem.  Thanks for reporting!

J

**Comment by I-NICO** [comment]
Have to correct myself: I meant ND not PFD.

**Comment by it0uchpods** [comment]
Working on it.... 

Might be fixed today.

J

**Comment by it0uchpods** [comment]
Update: this caused due a strange thing in the ND. I am still working on debugging this, as I can't understand why the arrow is not showing properly.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Got the fix, thanks to a nasal error submitted by D-SVEN. Just a few more ND fixes, and I'll be uploading it.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
![image](https://user-images.githubusercontent.com/25598604/32848570-cfbb03f0-c9fa-11e7-964d-6ce12e2f4027.png)
Fixed! 
I will fix soon the VOR2 info not displaying.

Kind Regards,
Josh
