### ISSUE TITLE
Request: Move audio and graphic files to git lfs

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#78]
Move audio and graphic files to git lfs to speed up git performance and reduce the repository size.
See [this link](https://github.com/git-lfs/git-lfs/wiki/Tutorial) for a tutorial.

I open the issue now cause the repo is about to exeede the recommended max size of 1GB.

**Comment by it0uchpods** [comment]
not an issue with the aircraft, so I'll close it, but I'll look into it when I have time.
