### ISSUE TITLE
MCDU INIT B page not locked

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#80]
### Expected Behavior
When ENGs are running INIT page B can't be accessed.

### Current Behavior
I can access the INIT B page while the ENGs are running.

### Possible Solution
Block access to INIT B when ENGs are running.

**Comment by Wecsje** [comment]
Hi, the MCDU is still in development, and thus very basic. In the upcomming weeks more work on the MCDU will be done, and this issue will then also be fixed.

Regards,

Charlie (Wecsje)

**Comment by it0uchpods** [comment]
Can you confirm this is actual behavior with the FCOM @Wecsje @legoboyvdlp ?
Thanks,
J

**Comment by Wecsje** [comment]
We are checking internally now with the FCOM.

C,

**Comment by Wecsje** [comment]
I can indeed confirm this is how it should behave. It's on the To-Do list.

C.

**Comment by it0uchpods** [comment]
Okay, great. I'll get that in soon.

Kind Regards,
Josh

**Comment by Wecsje** [comment]
Bug being solved as we speak, issue is closed.

**Comment by it0uchpods** [comment]
OK Fixed... 2 commits as I forgot to lock the right arrow.

If INITB is the current page, it won't revert to anything, until I figure out what the behavior is in such a situation.

Kind Regards,
Josh

**Comment by merspieler** [comment]
Looks good... just the `<->` in the top right corner should disapear since it indicates that there is another page which isn't the case while ENGs running.

**Comment by it0uchpods** [comment]
Should be easy enough to fix, I'll do tonight or tomorrow.

Thanks,
Josh
