### ISSUE TITLE
Incorrect NAV and Strobe lights

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#84]
### Expected Behavior
Strobe lights should doulbe flash

NAV lights should be only visable within the apropriate angle.
See this image for the NAV lights:  
![NAV light angle](https://s1.postimg.org/44trexa3bz/Unbenannt.png)

Correct behavior is explained in [this](https://www.youtube.com/watch?v=A1eqrunJuc0) video.

### Current Behavior
Strobe lights flash in a single flash.
NAV lights are shown from any angle (as long as it's not hidden by something eg. wing)

**Comment by Wecsje** [comment]
We are aware of this issue, and lots still needs to be done with the lighting (ie: project on ground). The apu exhaust strobe hasn't been added yet, but I'll make sure that atleast the strobe lighting behavior (flash twice) will be added today/tomorrow.

Regards,

Charlie (Wecsje)

**Comment by legoboyvdlp** [comment]
Hi @merspieler 
Where did you find that image? I'd love to see the source.
Did you try the ALS lights? They are only visible from the correct angle. I do not think it is possible to make the non-ALS lights visible from only a certain angle.

**Comment by merspieler** [comment]
The image is from the video I've linked (its about an A320).
I haven't enabled ALS since it make the water ugly... I might try that.

**Comment by merspieler** [comment]
That with the angle works fine with ALS but the strobe lights seem to not double flash... (I've checked that I have the latest version)

Another thing, probably a bug, is that the lights work even in cold & dark.

**Comment by it0uchpods** [comment]
They work in cold and dark because I've not yet tied them to the electrical system -- I'll do this soon -- please make a separate issue for such things.

J

**Comment by legoboyvdlp** [comment]
@merspieler 
https://github.com/it0uchpods/IDG-A32X/commit/26d957a4418cead719b7abeafbd9aefb3bd4d53f
3 hours ago

**Comment by merspieler** [comment]
I've seen that, I'll try adjusting the times to higher values, maybe the two flashes just look like merged into a longer one.

**Comment by legoboyvdlp** [comment]
Maybe... I only tested under ALS actually, and it looks fine to me?
I'll test without it shortly.

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/32553983-bc78fd4c-c46e-11e7-86a1-faebdf7e5c11.png)

**Comment by Wecsje** [comment]
Yes, that is something we need to change still, I'll reopen this issue, as the apu exhaust lights aren't done either.

C.

**Comment by merspieler** [comment]
OK

**Comment by it0uchpods** [comment]
What is the status of this @merspieler @legoboyvdlp ?

J

**Comment by it0uchpods** [comment]
OK, I'm considering this fixed.

Kind Regards,
Josh
