### ISSUE TITLE
APU - press START btn while running

### ISSUE THREAD

**Issue by Darkriser** [it0uchpods/IDG-A32X#85]
When APU is running and START btn shows green 'AVAIL', pressing the START btn again behaves strange.

### Expected Behavior
Actually, don't know what this does in a real aircraft :-)
I think - turn off the APU.

### Current Behavior
see lower ECAM - the EGT goes up to more than 700dg, then slowly goes back to standard cca 350dg.

### Possible Solution
no clue, sry...

### Steps to Reproduce
1. start APU as usual (BAT or EXT PWR, MASTER SW then START and wait until AVAIL)
2. show APU page on lower ECAM
3. press START btn again
4. watch EGT

**Comment by Wecsje** [comment]
Hi,

The EGT shouldn't relight again, this is a bug. After starting, this button basically doesn't do anything, to turn it off, just press the master.

Regards,

Charlie

**Comment by it0uchpods** [comment]
OK, thanks. Will fix that ASAP.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Fixed.

Thanks and Kind Regards,
Josh
