### ISSUE TITLE
Wired Cabin lights

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#86]
### Current Behavior
Depending on the angle of the Rudder the Cabinlights turns of and on.

### Steps to Reproduce
1. Start fg at night
2.  Go to outside view
3. Turn the rudder to the right and watch the cabin windows.

**Comment by Wecsje** [comment]
I think I may have seen this aswell, we will investigate further.

C.

**Comment by it0uchpods** [comment]
Yeah that is weird... investigating now.

J

**Comment by it0uchpods** [comment]
Found the issue, it was using an old multiplayer property that controls steering now, used to control lighting in the plane this interior is from.

Fixed.

Thanks and Kind Regards,
Josh
