### ISSUE TITLE
FG:PropertyValue::GetValue() The property/systems/electrical/bus/ac1 does not exist

### ISSUE THREAD

**Issue by J4i1310** [it0uchpods/IDG-A32X#89]
### Steps to Reproduce

1.
2.
3.
4.

**Comment by it0uchpods** [comment]
Remove -master, and fill out the template please if the issue still exists, on my system all is fine.

**Comment by captaintripleseven** [comment]
Can you tell me how to fix it? I cant

**Comment by it0uchpods** [comment]
Read what I wrote above ^

J

**Comment by captaintripleseven** [comment]
I know you wrote that but can you help exactly what to type in and where?


Josh Davidson <notifications@github.com> ezt írta (időpont: 2019. ápr. 19.,
Pén 23:35):

**Comment by legoboyvdlp** [comment]
Remove -master from the folder name.

**Comment by captaintripleseven** [comment]
Is it okay if I remove -main? Mine isnt -master

Jonathan Redpath <notifications@github.com> ezt írta (időpont: 2019. ápr.
20., Szo 11:10):

**Comment by it0uchpods** [comment]
No, you aren't listening. If you remove -main everything will break and the plane will no longer show up in the launcher.

When you download the Airbus from GitHub, it will download as IDG-A32X-master.zip
You extract it, you get a folder named IDG-A32X-master. You need to rename this folder to IDG-A32X.

Read INSTALL.md: https://github.com/it0uchpods/IDG-A32X/blob/master/INSTALL.md

Kind Regards,
Josh

**Comment by captaintripleseven** [comment]
Now I understand, thank you very much!

Josh Davidson <notifications@github.com> ezt írta (időpont: 2019. ápr. 20.,
Szo 20:30):

**Comment by it0uchpods** [comment]
You're welcome! Enjoy!

Kind Regards,
Josh
