### ISSUE TITLE
A320 does not lock onto ILS 

### ISSUE THREAD

**Issue by bob755** [it0uchpods/IDG-A32X#89]
The AP is set to lock  onto yhe ILS 31R of LFMT.
The approach angle was 10deg

The   ILS frequency and RWY 
### Expected Behavior
The hdg should change to align with 31R

### Current Behavior ILS
The aircraft continues with the current hdg

### Steps to Reproduce
1. AP settings: AP1 on, LS on, FD on, LOC on
2.  ILS frequency  108.55 and CRS 310  set on the MCDU
3. Approach angle 10deg . Alt 3000ft

![capture](https://user-images.githubusercontent.com/33560670/32702339-0830e7e8-c7e6-11e7-98eb-9f870802d1fa.PNG)

**Comment by it0uchpods** [comment]
Did you press LOC when you were INSIDE the localizer? Or did you press it before entering the ILS?

**Comment by bob755** [comment]
I pressed LOC when I saw the localiser indicator appear at the bottom of the PFD

**Comment by it0uchpods** [comment]
Will try to reproduce.

J

**Comment by bob755** [comment]
Could there be a problem wih this particular airport? It's the first time I used this ILS

**Comment by bob755** [comment]
Just to onfirm, I tried exactly the same maneuver with an A319neo and it locked int the localiser even when the hdg was at almost 90deg to the RWY

**Comment by it0uchpods** [comment]
OK. I've moved my new localizer capture system up in priority, I'll check it out. If you try intercepting closer to the airport, it will work. I know the issue and was able to reproduce it earlier today.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Please try it now.

Note that the FGFS Localizer goes out further than good signal, so my realistic autopilot does not catch it if you are WAY to far out, even if inside the circle. Next time check Debug --> Browse Internal Properties, go to /instrumentation/nav[0]/signal-quality-norm

If it is less than 0.99, then the localizer signal is not strong enough to capture (in real aircraft this problem would also appear, but the signal won't show up at all then)

Kind Regards,
Josh

**Comment by bob755** [comment]
My FG is broken for some reason!! It won't run from the launcher anymore so reinstalling.  As soon as it's up and running again, I'll test the localizer

**Comment by it0uchpods** [comment]
Oh, that's sad. Please do let me know the outcome. 

Kind Regards,
Josh

**Comment by bob755** [comment]
My FG is repaired and I re-ran the test after downloading the updated verion (revision 3064)
Unfortunately it still doesn't lock on  to the localiser.  The localiser indicator is visble.
The screenshot shows just after crossing the ILS path.
![image](https://user-images.githubusercontent.com/33560670/32773343-202d903c-c929-11e7-9731-4fbe115fbac3.png)
![image](https://user-images.githubusercontent.com/33560670/32773393-4d3f8a26-c929-11e7-9210-985f436cbe46.png)
![image](https://user-images.githubusercontent.com/33560670/32773405-59645016-c929-11e7-8df0-461ba0edb63a.png)

**Comment by bob755** [comment]
More tests:
I flew to a nearby airport to the west LFMU and it locked fine onto this localizer. 
I then flew back to LFMT.  I saw NAV2 was set to the ILS of another airport to the north that you can see on the map so I changed the NAV2 frequency in case that was having an effect.
It still didn't lock onto the LFMT localizer. So there is definately a problem with this airport. However  the A320neo does lock onto this localizer.

**Comment by it0uchpods** [comment]
Hi
NAV2 in the radio dialog is not used by the Airbus. NAV1 is the ILS frequency.

I will check that airport today. It is worth noting, that my AP will capture the localizer in a realistic way, so, if there is a problem with that airport, it will not capture.

Kind Regards,
Josh

**Comment by bob755** [comment]
FYI, it locked on to the localizer the other side of the runway i.e on 13L not 31R and turned hdg 130

**Comment by it0uchpods** [comment]
I did an 11nm intercept.
It captured, and is now stable descending on glideslope at around 9nm
![image](https://user-images.githubusercontent.com/25598604/32786705-b624a5be-c922-11e7-9965-aa4ee77a76f5.png)

It works for me, so I don't know your problem.

Kind Regards,
Josh

**Comment by Wecsje** [comment]
In real life, the ILS frequency is intercepted at the end of the thingie in FG, check charts to know which waypoint, at which altitude it should be intercepted.

**Comment by bob755** [comment]
That's really strange.

**Comment by it0uchpods** [comment]
I am using terraGIT scenery, and Navigraph data upgrade. Maybe, this error was corrected in terraGIT?

Kind Regards,
Josh

**Comment by bob755** [comment]
I see that your map is not the same.  You have RWYs 12L and 30R. I checked real airport charts and those are correct.
That must be the explanation. Phew!
Anyway, thanks for looking at this.

**Comment by bob755** [comment]
I did download the scenery using terramaster.  Is that correct?

**Comment by it0uchpods** [comment]
No problem.

I used terraGIT: http://thejabberwocky.net/viewtopic.php?f=51&t=627

It is the best scenery system in my opinion.

Kind Regards,
Josh

**Comment by bob755** [comment]
Is this where the ILS data is contained?

**Comment by it0uchpods** [comment]
No, terraGIT is scenery, but it contains better developed scenery than terraSync/master.

scenery contains ILS information also, as does navdata. (it could be my navigraph fixing it also).

Kind Regards,
Josh

**Comment by bob755** [comment]
So I might have to pay to get the corrected ILS information! :-)

**Comment by it0uchpods** [comment]
Well, not only that, but you will get SIDs/STARs and approaches in Route Manager, or later MCDU instead of DEFAULT. :) and $30 a year it's not bad.

But try terraGIT first. It might fix it.

Kind Regards,
Josh

**Comment by bob755** [comment]
Sorry to drag this issue on which is is probably not an problem with the aircraft anyway but I'd really like to try and figure out why this is happening.
I downloaded terraGIT terrain,  objects and airports for this region (e000n40) but LFMT still has RWYs 13L and 31R whereas I see you have 12L and 30R. I haven't tested the ILS yet.
Thanks
