### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#90]
### Current Behavior
Crashed while approaching ILS EDDM 26L with APPR, HDG and ALT enabled.

Backlog:
```
Nasal runtime error: undefined symbol: RouteDriver
  at /games/FlightGear 2017.3.1/data/Aircraft/IDG-A32X/Models/Instruments/ND/canvas/map/RTE.lcontroller, line 33
  called from: /games/FlightGear 2017.3.1/data/Aircraft/IDG-A32X/Models/Instruments/ND/canvas/framework/canvas.nas, line 220
  called from: /games/fg-linux/install/flightgear/fgdata/Nasal/canvas/MapStructure.nas, line 1034
  called from: /games/fg-linux/install/flightgear/fgdata/Nasal/canvas/MapStructure.nas, line 928
  called from: /games/FlightGear 2017.3.1/data/Aircraft/IDG-A32X/Models/Instruments/ND/canvas/framework/canvas.nas, line 57
  called from: __canvas:canvas-map, line 115
Running FlightGear's terminate handler. The program is going to exit due to a fatal error condition, sorry.
Aborted
```

**Comment by it0uchpods** [comment]
OK, thanks... I'm looking into it. I don't think the nasal error was related to the crash, that type of error doesn't make FG Close/Crash AFAIK.

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
I do not able to reproduce this nasal error. Everything looks as it should in the code.

Closing until someone else can reproduce this.

Kind Regards,
Josh

**Comment by merspieler** [comment]
I've done some more testing and it seems like the nasal error has nothing to do with `Running FlightGear's terminate handler. The program is going to exit due to a fatal error condition, sorry.
Aborted` which occured today again when the NAV mode refused to go back to HDG mode.
