### ISSUE TITLE
Model not showing up

### ISSUE THREAD

**Issue by Flightgearhelp** [it0uchpods/IDG-A32X#90]
### Expected Behavior

The cockpit is not showing up as it should, was working yesterday but not now
### Current Behavior

I can just see past the view, in cockpit veiw I can see the runway without the model in my sight.
### Possible Solution

I reloaded the model and still no luck
### Steps to Reproduce

1.
![Screen Shot 2019-04-17 at 1 52 29 pm](https://user-images.githubusercontent.com/46958999/56264169-32bf0680-6118-11e9-8129-493feac2e733.png)

2. I tried to reload the model in the debug page but no luck...
3.I did have this issue earlier with the a330 model but I downloaded the latest version and it got fixed, but I'm not sure whether mine is the latest because it will tell me my model is outdated.
4.

**Comment by Flightgearhelp** [comment]
Sorry I forget to tell how to reproduce, 

1. Fly with any IDG model
2. Do not change views during load up
3.You should end up like the picture above...

**Comment by legoboyvdlp** [comment]
Please follow INSTALL.MD.

**Comment by it0uchpods** [comment]
Well, we would never let such a mistake through QC, so this is probably an issue on your install. If you follow INSTALL.md, you should get a full working plane. You can also try a re-download.
Until then, closing.

Kind Regards,
Josh

**Comment by Flightgearhelp** [comment]
I did remove the master bit from the file,   + I redownloaded the aircraft and it is working fine, sorry for the hassle!

**Comment by it0uchpods** [comment]
No worries! Enjoy the Airbus!

Kind Regards,
Josh
