### ISSUE TITLE
PFD doesn't work properly in manual start

### ISSUE THREAD

**Issue by cpinheiro26** [it0uchpods/IDG-A32X#91]
### General
----

I am submitting a: (select one) 
* [x] Bug report
* [ ] Feature request

### Details
When in manual start A32X or A33X the pfd doesn't show the "artifical horizon" 
and shows only "ATT" in the middle of the screen in red with a black background. 
Even if I do the IRS align it doesn't work

#### Expected Behavior (bug reports)

Display the artificial horizon as in the auto start mode. 

#### Current Behavior (if applicable)

"ATT" displayed in the artificial horizon screen.

#### Requested Behavior  (feature requests)

Display the artificial horizon

#### Possible Solution (if applicable)

N.A.

#### Steps to Reproduce (bug reports)

1. Turn on aircraft batteries
2. Turn on the APU master switch
3. Turn on the APU
4. Wait for the screen appear

**Comment by it0uchpods** [comment]
Hi,
You must press the ALIGN button on the MCDU INIT page to give the ADIRU the position to align too. (FMGC button, then wait, then press INIT once the status page appears, then put your departure/destination, then push the align)

Kind Regards,
Josh
