### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#92]
I've got a few questions...

I thought about contributing a bit to the ecam messages on the upper ecam...
Where would be the best place to do that?
Are there any good sources/tutorials for nasal (my search engine of least distrust didn't help)?

Do you have an IRC channel? I'm asking cause @it0uchpods has his IRC name in the fg forum but I haven't found him in the freenode nor the flightgear IRC network.

**Comment by it0uchpods** [comment]
Hi merispieler
These things are best put in the forums -- not here.

I will quote you, and answer there.

Kind Regards,
Josh

**Comment by merspieler** [comment]
Too bad... I won't ever use Slack cause of its policy...
And for contributing... The ECAM msgs would be the thing, where I now what I'ld have to do.
If I can contribute anything else, tell me and I'll take a look at it.

**Comment by legoboyvdlp** [comment]
Try posting on the forums, not slack. ;)
