### ISSUE TITLE
MCDU: input repeats

### ISSUE THREAD

**Issue by legoboyvdlp** [it0uchpods/IDG-A32X#95]
When I input MCDU input with low framerate, the input tends to have repeated digits. 
### Expected Behavior
Input into MCDU should not be repeated

### Current Behavior
For instance, putting in EHAM/EBBR today gave me EHHHAAAM///EBBBBRRRR
### Possible Solution
Try setting <repeatable> to false in .xml?

### Steps to Reproduce
Put text into MCDU, with low framerate

**Comment by it0uchpods** [comment]
FGFS pick animation issue... unfixable by me.

Kind Regards,
Josh
