### ISSUE TITLE
IT-GUI style makes Automatic Download of Scenery and Data log unreadable

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#96]
### Expected Behavior
Font has a diffrent color.

### Current Behavior
The font color is black and the bg as well which makes it unreadable.

### Possible Solution
Change the color of the log text.

### Steps to Reproduce
1. Click File->Scenery Download
2. Click Log
3. Fly over some aera where you've never been befor so the log fills with some information.

**Comment by it0uchpods** [comment]
I do not find this to be an issue. As far as I know, the logging object doesn't allow modifications (yet), sadly. I don't think it's an issue, as you can see if if you look from certain angles, you can read it. Plus, the log is saved on your PC also (IIRC), so you can just look there. I will keep trying to find solutions for this, but it is not my priority right now.

Kind Regards,
Josh
