### ISSUE TITLE
Incorrect ND in nav mode

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#97]
### Expected Behavior
As soon as NAV mode is entered the route has to be solid instead of dashed (dashed route = route active but flying with HDG mode or manually)
As well the stright green line showing the true flight direction and the HDG bug should disapear.
Should look like [this](http://www.airsimtech.eu/tl_files/screenshots/nd/NDGND.jpg).

### Current Behavior
The route stays dashed and the stright line and the HDG bug don't disapear

### Steps to Reproduce
1. Create a route
2. Compare HDG to NAV mode

**Comment by it0uchpods** [comment]
Was aware of this, just didn't have the time to do it yet.

Kind Regards,
Josh

**Comment by merspieler** [comment]
I thought that you probably knew that issue but since it has driven me crazy (thinking I'm in HDG mode and allways recheck it) I opened the issue.

**Comment by it0uchpods** [comment]
Fixing it right now :)

J

**Comment by it0uchpods** [comment]
Fixed :)

Heading bug hides properly, and route line becomes constant. I also matched up the colors with my other displays.

Kind Regards,

**Comment by merspieler** [comment]
I wouldn't consider this bugas fully fixed cause when airborn, the AP is in NAV mode but OFF then the line has to be still dashed and the predicted trajectory has to be shown like in HDG mode.

**Comment by it0uchpods** [comment]
I don't think that is correct. It should go solid when the Flight Director is on also in NAV mode according to my research.

Kind Regards,
Josh

**Comment by merspieler** [comment]
I'll do my own research on that... but it's hard to fly without that trajectory

**Comment by it0uchpods** [comment]
How so, if the FD is on, follow the flight director???

Kind Regards,
Josh

**Comment by merspieler** [comment]
Semi valid argument but imagine an appr which you can only fly manually... bt still keep NAV mode for go around enabled

**Comment by it0uchpods** [comment]
You don't keep NAV on in that situation, and in a go around, the engagement of TOGA would cause RWY or HDG to appear anyways, if the FDs are on. For fully manual (visual) approaches, Flight Directors are turned off.

Kind Regards,
Josh
