### ISSUE TITLE
LDG LT behaves strange

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#98]
### Expected Behavior
LDG LT allways lights in the same direction.
### Current Behavior
When looking around using the mouse, the light moves slightly (only noticeable near markings).
When looking around using the joystick, the light follows the view eg. looking out of the left window, the LDG LT shines to the left instead of stright ahead.

### Steps to Reproduce
1. Start fg at night, preferable on a runway cause of the markings.
2. Look around using the mouse and observe the light on the ground (look at the edges)
3. Look around using the joystick

**Comment by Wecsje** [comment]
Hi, we are already aware of this issue, and it is on the list (including reflections for all the other lights). I can however not say when this will be done.

C.

**Comment by merspieler** [comment]
OK... if you keep unsolved issues open, duplicates are less likely to happen ;-)
