### ISSUE TITLE
Acceleration ALT not allways recogniced

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#99]
### Expected Behavior
Passing the ACC ALT the SPD in managed mode should increase

### Current Behavior
Sometimes it stays at the SPD of initial climb

### Steps to Reproduce
1. Start at almost sea level (at least there I've found the problem)
2. set in the MCDU CRZ ALT to `40` and THR RED/ACC to `3500/3500`
3. perform a normal start
4. when reaching CRZ ALT the ACC ALT doesn't seem to be reached

**Comment by it0uchpods** [comment]
Screenshot and value of FMGC/status/phase, and please tell me all FMAs, Pitch, Roll, Thrust

J

**Comment by merspieler** [comment]
I've recorded a [video](https://vimeo.com/244398510) (You can see how unplaned I'm and I've almost forgot to set the crz alt manually... :D)
With the FMGC/status/phase... I've realised after recording what you've ment... but it's 0 until the start of the TO run and then it stays 1.

**Comment by it0uchpods** [comment]
Got it. You went from SRS to ALT CRZ, so it never transitioned to climb. I will fix that now. :)

Kind Regards,
Josh

**Comment by it0uchpods** [comment]
Should be fixed, report if not. 

Kind Regards,
Josh
